This notebook explores the yahoo finance api 

This covers:
-Set up a ticker
- Look at recomendations for that ticker
- Look at information provided (such as industry, full time employees etc)

In [1]:
import pandas as pd
import numpy as np
import yfinance as yf
from autoIG import epics

In [2]:
gold = yf.Ticker(epics.GOLD_TICKER)
msft = yf.Ticker(epics.MSFT_TICKER)

In [5]:
epic = yf.Ticker(epics.BITCOIN_TICKER)

In [6]:
# we can get industry recomendations
epic.recommendations

In [7]:
# information
import pprint
print(f"Size of info dictionary: {len(epic.info.keys())}")
pprint.pprint(epic.info,indent = 2)

Size of info dictionary: 70
{ 'algorithm': None,
  'ask': None,
  'askSize': None,
  'averageDailyVolume10Day': 20760041585,
  'averageVolume': 35006490885,
  'averageVolume10days': 20760041585,
  'beta': None,
  'bid': None,
  'bidSize': None,
  'circulatingSupply': 19229992,
  'coinMarketCapLink': 'https://coinmarketcap.com/currencies/bitcoin',
  'companyOfficers': [],
  'currency': 'USD',
  'dayHigh': 17216.826,
  'dayLow': 17131.363,
  'description': 'Bitcoin (BTC) is a cryptocurrency . Users are able to '
                 'generate BTC through the process of mining. Bitcoin has a '
                 'current supply of 19,229,343. The last known price of '
                 'Bitcoin is 17,163.70561387 USD and is down -0.53 over the '
                 'last 24 hours. It is currently trading on 9873 active '
                 'market(s) with $19,719,971,333.68 traded over the last 24 '
                 'hours. More information can be found at '
                 'https://bitcoin.org/.',
  'dividendRate': None,
  'dividendYield': None,
  'exDividendDate': None,
  'exchange': 'CCC',
  'exchangeTimezoneName': 'UTC',
  'exchangeTimezoneShortName': 'UTC',
  'expireDate': None,
  'fiftyDayAverage': 18047.771,
  'fiftyTwoWeekHigh': 51956.33,
  'fiftyTwoWeekLow': 15599.047,
  'fiveYearAvgDividendYield': None,
  'forwardPE': None,
  'fromCurrency': 'BTC',
  'gmtOffSetMilliseconds': '0',
  'isEsgPopulated': False,
  'lastMarket': 'CoinMarketCap',
  'logo_url': 'https://logo.clearbit.com/Bitcoin.com',
  'market': 'ccc_market',
  'marketCap': 330867441664,
  'maxAge': 1,
  'maxSupply': None,
  'messageBoardId': 'finmb_BTC_CCC',
  'name': 'Bitcoin',
  'navPrice': None,
  'open': 17138.012,
  'openInterest': None,
  'payoutRatio': None,
  'preMarketPrice': None,
  'previousClose': 17138.012,
  'priceHint': 2,
  'priceToSalesTrailing12Months': None,
  'quoteType': 'CRYPTOCURRENCY',
  'regularMarketDayHigh': 17216.826,
  'regularMarketDayLow': 17131.363,
  'regularMarketOpen': 17138.012,
  'regularMarketPreviousClose': 17138.012,
  'regularMarketPrice': 17205.803,
  'regularMarketVolume': 14029858816,
  'shortName': 'Bitcoin USD',
  'startDate': 1367107200,
  'strikePrice': None,
  'symbol': 'BTC-USD',
  'toCurrency': 'USD=X',
  'totalAssets': None,
  'tradeable': False,
  'trailingAnnualDividendRate': None,
  'trailingAnnualDividendYield': None,
  'trailingPegRatio': None,
  'twoHundredDayAverage': 21080.908,
  'volume': 14029858816,
  'volume24Hr': 14029858816,
  'volumeAllCurrencies': 14029858816,
  'yield': None,
  'ytdReturn': None}

In [8]:
# Stock splits
epic.actions.head()

Empty DataFrame
Columns: [Dividends, Stock Splits]
Index: []

In [14]:
history_raw = epic.history(interval='1m',end = '2022-12-10',start='2022-12-05')

# history_raw.to_csv('tmp/history_raw.csv')

In [17]:
history_raw.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2022-12-05 00:00:00+00:00,17128.894531,17128.894531,17128.894531,17128.894531,0,0,0
2022-12-05 00:01:00+00:00,17122.783203,17122.783203,17122.783203,17122.783203,0,0,0
2022-12-05 00:02:00+00:00,17118.808594,17118.808594,17118.808594,17118.808594,0,0,0
2022-12-05 00:03:00+00:00,17114.835938,17114.835938,17114.835938,17114.835938,1974272,0,0
2022-12-05 00:04:00+00:00,17106.041016,17106.041016,17106.041016,17106.041016,0,0,0

In [24]:
def mutate_history(df):
    df['days_since'] =(df.index - df.index[0]).days
    return df
history = mutate_history(history_raw)
history.head(3)

,Open,High,Low,Close,Volume,Dividends,Stock Splits,days_since
Date,,,,,,,,
2022-10-13 00:00:00-04:00,1675.199951,1675.300049,1641.500000,1670.000000,729,0,0,0
2022-10-14 00:00:00-04:00,1665.300049,1667.000000,1640.000000,1641.699951,82,0,0,1
2022-10-17 00:00:00-04:00,1650.199951,1657.000000,1646.800049,1657.000000,238,0,0,4